plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.chuck.paginationscrollviewdemo'
    compileSdk 33

    defaultConfig {
        applicationId "com.chuck.paginationscrollview"
        minSdk 24
        targetSdk 33
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
//        release { // 推荐定义一个release版本的签名配置
//            storeFile file('./signature/platform.jks') // 例如: file("myreleasekey.jks")
//            storePassword 'android' // 例如: "123456"
//            keyAlias 'android' // 例如: "my_alias"
//            keyPassword 'android' // 例如: "123456"
//        }
//        // 你也可以同样定义一个debug配置，用于调试版本签名
//        debug {
//            storeFile file('./signature/platform.jks') // 例如: file("myreleasekey.jks")
//            storePassword 'android' // 例如: "123456"
//            keyAlias 'android' // 例如: "my_alias"
//            keyPassword 'android' // 例如: "123456"
//        }

        release { // 推荐定义一个release版本的签名配置
            storeFile file('./signature/phone_qk_platform.jks') // 例如: file("myreleasekey.jks")
            storePassword '111111' // 例如: "123456"
            keyAlias 'thh' // 例如: "my_alias"
            keyPassword '111111' // 例如: "123456"
        }
        // 你也可以同样定义一个debug配置，用于调试版本签名
        debug {
            storeFile file('./signature/phone_qk_platform.jks') // 例如: file("myreleasekey.jks")
            storePassword '111111' // 例如: "123456"
            keyAlias 'thh' // 例如: "my_alias"
            keyPassword '111111' // 例如: "123456"
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            signingConfig signingConfigs.debug
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    lintOptions {
        ignoreWarnings true
        abortOnError false
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.7.0'
    implementation 'androidx.appcompat:appcompat:1.4.1'
    implementation 'com.google.android.material:material:1.5.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.3'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'

    implementation files('libs/router_20251227_1.0.0.jar')
    implementation files('libs/utils_20251227_1.0.0.jar')
    implementation(name: 'data_persistence_20251227_1.0.0', ext: 'aar')
    implementation(name: 'item_foundation_20251227_1.0.0', ext: 'aar')
    implementation(name: 'paginationscrollview_20251227_1.0.0', ext: 'aar')
    implementation(name: 'popup_exchange_20251227_1.0.0', ext: 'aar')
}